server:
  port: 8090
spring:
  application:
    name: main
  datasource:
    url: jdbc:postgresql://localhost:5432/itracourse
    username: postgres
    password: Israel1997Israel
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-main.xml
  jpa:
    show-sql: true

security:
  oauth2:
    client:
      clientId: 528747818999-j4dif2jeospb281gqnhedhjo72ltob66.apps.googleusercontent.com
      clientSecret: 8Oqk__1Q-qBDCkzl7KzS4I5G
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid,email,profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true

hibernate:
  default:
    directory_provider: filesystem
    indexBase: /data/index/default

